spring:
  rabbitmq:
    host: 192.168.56.101
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1  #一次拉取一條消息，用於消費端限流上
